config/routes.rb
Rails.application.routes.draw do
  root to: 'sessions#new'
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show]
  resources :feeds do
    collection do
      post :confirm
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/feed.rb
class Feed < ApplicationRecord
  mount_uploader :image, ImageUploader
  validates :content, presence: true
  validates :image, presence: true
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: true
  before_validation { email.downcase! }
  has_secure_password
  validates :password, length: { minimum: 6 }
  has_many :feeds
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  before_action :login_required
  private
  def login_required
    redirect_to new_session_path unless current_user
  end
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_action :set_feed, only: [ :show, :edit, :update, :destroy ]
  def new
    if params[:back]
      @feed = Feed.new(feed_params)
    else
      @feed = Feed.new
    end
  end
  def index
    @feeds = Feed.all
  end
  def create
    @feed = current_user.feeds.new(feed_params)
    if @feed.save
      redirect_to feeds_path, notice: "投稿をしました！"
    else
      render :new
    end
  end
  def show
  end
  def edit
    if @feed.user_id == current_user.id
      render "edit"
    else
      redirect_to feeds_path
    end
  end
  def update
    if @feed.update(feed_params)
      redirect_to feeds_path notice: "投稿を編集しました"
    else
      render :edit
    end
  end
  def destroy
    if @feed.user_id == current_user.id
      @feed.destroy
      redirect_to feeds_path, notice: "投稿を削除しました"
    else
      redirect_to feeds_path
    end
  end
  def confirm
    @feed = current_user.feeds.new(feed_params)
    render :new if @feed.invalid?
  end
  private
  def feed_params
    params.require(:feed).permit(:content, :image, :image_cache)
  end
  def set_feed
    @feed = Feed.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  def new
  end
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end
  def destroy
    session.delete(:user_id)
    flash[:noteice] = "ログアウトしました"
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  def new
    @user = User.new
  end
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id), notice: "アカウントを作成しました！"
    else
      render :new
    end
  end
  def show
    @user = User.find(params[:id])
  end
  private
  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'create'
      confirm_feeds_path
    elsif action_name == 'edit'
      feed_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/feeds/_form.html.erb
<div class="main_feed">
  <%= form_with(model: @feed, local: true, url: choose_new_or_edit) do |form| %>
  <% if @feed.errors.any? %>
  <div id="error_explanation">
    <h2><%= @feed.errors.count %>件のエラーがあります。</h2>
    <ul>
      <% @feed.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
  <main class="detail">
    <%= form.label :content %>
    <%= form.text_field :content %>
    <%= form.label :image %>
    <%= image_tag(@feed.image.url) if @feed.image && @feed.image.url %>
    <label class="detail">
      <%= form.file_field :image %>
      <%= form.hidden_field :image_cache %>
    </label>
    <div class="actions">
      <%= form.submit %>
    </div>
    <% end %>
    <%= link_to 'みんなの投稿をみよう！', feeds_path %>
  </main>
</div>

app/views/feeds/confirm.html.erb
<h1>この投稿内容でよろしいですか？</h1>
<%= form_with(model: @feed, url: feeds_path, local: true) do |form| %>
<%= form.hidden_field :content %>
<%= form.hidden_field :image_cache %>
  <p>Content:<%= @feed.content %></p>
  <%= image_tag(@feed.image.url) if @feed.image && @feed.image.url %>
  <%= form.submit "投稿する" %>
<% end %>
<%= form_with(model:@feed, url:new_feed_path, local:true, method: "get") do |form|%>
  <%= form.hidden_field :content %>
  <%= form.hidden_field :image_cache %>
  <%= form.submit "戻る", name: "back" %>
<% end %>

app/views/feeds/edit.html.erb
<h2 class="detail">投稿の編集</h2>
<%= render 'form' %>

app/views/feeds/index.html.erb
<main class="post_list">
  <h1>みんなの投稿をみよう！</h1>
  <table>
    <tr>
      <th>Content</th>
      <th>image</th>
    </tr>
    <% @feeds.each do |feed| %>
    <tr>
      <td><%= feed.content %></td>
      <td><%= image_tag feed.image.url %></td>
      <td><%= feed.user.name %></td>
      <td><%= link_to '詳細を確認する', feed_path(feed.id) %></td>
      <% if feed.user_id == current_user.id %>
      <td><%= link_to '投稿の編集をする', edit_feed_path(feed.id) %></td>
      <td><%= link_to '投稿を削除する', feed_path(feed.id), method: :delete %></td>
      <% end %>
    </tr>
    <% end %>
  </table>
  <%= link_to '新しい投稿をする', new_feed_path %>
</main>

app/views/feeds/new.html.erb
<h2 class="detail">コメントと写真をアップしてね！</h2>
<%= render 'form' %>

app/views/feeds/show.html.erb
<main class="detail">
  <h1>投稿詳細画面</h1>
  <p>Content: <%= @feed.content %></p>
  <p>image: <%= image_tag @feed.image.url %></p>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FriendApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <ul>
      <% if logged_in? %>
        <li><%= link_to "Profile", user_path(@current_user.id)%></li>
        <li><%= link_to "Logout", session_path(@current_user.id), method: :delete %></li>
        <li><%= link_to "投稿をする", new_feed_path %></li>
        <li><%= link_to "投稿一覧", feeds_path %></li>
      <% else %>
        <li><%= link_to "Sing up", new_user_path %></li>
        <li><%= link_to "Login", new_session_path %></li>
      <% end %>
    </ul>
    <% flash.each do |key, value| %>
    <%= content_tag(:div,value,class:"#{key}")%>
    <% end %>
    </header>
    <%= yield %>
    <footer>
      <p>運営会社 友だちとつながる 株式会社</p>
      <p>© 2021- Connect with Friends Corp.</p>
    </footer>
  </body>
</html>

app/views/users/new.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error")%>
            prohibited this<%= @user.name %> from being saved:</h2>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<main class="sing_up">
  <div class="">
    <h1 class="sing_up_title">Sign up</h1>
    <%= form_with(model: @user, local:true ) do |f| %>
      <div class="sign_up_form ">
        <div class="sing_up_name">
          <%= f.label :name %>
          <%= f.text_field :name %>
        </div>
        <div class="sing_up_email">
          <%= f.label :email %>
          <%= f.email_field :email %>
        </div>
        <div class="sing_up_password">
          <%= f.label :password %>
          <%= f.password_field :password %>
        </div>
        <div class="sing_up_password_confirmation">
          <%= f.label :password_confirmation %>
          <%= f.password_field :password_confirmation %>
        </div>
        <div class="sing_up_submit">
          <%= f.submit "Create my account", class: 'btn btn-primary' %>
        </div>
      <div>
    <% end %>
  </div>
</main>

app/views/users/show.html.erb
<main class="detail">
  <h1><%= @user.name %>のページ</h1>
  <p>メールアドレス: <%= @user.email %></p>
</main>